-- Fichier SQL de test pour la table boutique
-- Basé sur les données réelles de la plateforme MadeinConflans

-- Suppression des données de test existantes (optionnel)
-- DELETE FROM boutique WHERE demo = true;

-- Insertion de boutiques de test
INSERT INTO boutique (
  name_shop,
  address_shop,
  tel_shop,
  email_shop,
  formule_shop,
  uid,
  actif,
  photo_url,
  slug,
  categories_shop,
  limite,
  lot,
  longitude,
  latitude,
  description_shop,
  siteweb_store,
  facebook_shop,
  instagram_shop,
  tiktok_shop,
  youtube_shop,
  horaire_shop,
  logo_shop,
  tag_shop,
  scan_uid,
  madeinconflans,
  statut,
  google_maps_shop,
  check_location,
  subscription,
  active_adresse,
  vip,
  pub,
  validation_point,
  scan_24h,
  avis_google,
  lien_avis_google,
  enable_auto_messages,
  message_1_point,
  message_recompense,
  demo
) VALUES

-- Boutique 1: Restaurant Italien
(
  'La Pizzeria du Centre',
  '15 Rue de la République, 78700 Conflans-Sainte-Honorine',
  '0130123456',
  'contact@pizzeria-centre.fr',
  '1 pizza offerte au 5ème passage',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
  'pizzeria-centre',
  'Restaurant',
  '5',
  '1 pizza offerte',
  '2.090000',
  '48.990000',
  'Authentique pizzeria italienne au cœur de Conflans. Nos pizzas sont préparées avec des ingrédients frais et cuites au feu de bois.',
  'https://www.pizzeria-centre.fr',
  'https://www.facebook.com/pizzeria-centre',
  'https://www.instagram.com/pizzeria-centre',
  NULL,
  NULL,
  'Lundi au samedi : 11h30 - 14h30 et 18h30 - 22h30',
  'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200',
  'pizzeria, italien, restaurant',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/pizzeria-centre',
  true,
  'https://maps.app.goo.gl/example1',
  false,
  false,
  true,
  '1',
  false,
  false,
  true,
  false,
  NULL,
  true,
  'Félicitation pour votre premier point de fidélité !',
  'Bravo ! Vous avez gagné une pizza offerte. Présentez ce message en boutique.',
  true
),

-- Boutique 2: Coiffeur
(
  'Salon Coiffure Élégance',
  '42 Avenue Carnot, 78700 Conflans-Sainte-Honorine',
  '0130987654',
  'contact@salon-elegance.fr',
  '10% de réduction au 3ème passage',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800',
  'salon-elegance',
  'Beauté',
  '3',
  '10% de réduction',
  '2.095000',
  '48.992000',
  'Salon de coiffure moderne proposant des coupes tendances et des soins capillaires de qualité.',
  'https://www.salon-elegance.fr',
  NULL,
  'https://www.instagram.com/salon-elegance',
  NULL,
  NULL,
  'Mardi au samedi : 9h - 19h',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200',
  'coiffure, beauté, salon',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/salon-elegance',
  true,
  'https://maps.app.goo.gl/example2',
  false,
  true,
  true,
  '1',
  true,
  false,
  false,
  false,
  NULL,
  false,
  'Merci pour votre fidélité !',
  'Profitez de 10% de réduction sur votre prochaine coupe.',
  true
),

-- Boutique 3: Boulangerie
(
  'Boulangerie Artisanale',
  '8 Place de la Mairie, 78700 Conflans-Sainte-Honorine',
  '0130554433',
  'contact@boulangerie-artisanale.fr',
  '1 croissant offert pour 10 achats',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
  'boulangerie-artisanale',
  'Alimentation',
  '10',
  '1 croissant offert',
  '2.088000',
  '48.991000',
  'Boulangerie artisanale proposant pains, viennoiseries et pâtisseries fait maison avec des produits locaux.',
  NULL,
  'https://www.facebook.com/boulangerie-artisanale',
  NULL,
  NULL,
  NULL,
  'Lundi au dimanche : 6h30 - 19h30',
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200',
  'boulangerie, pain, viennoiserie',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/boulangerie-artisanale',
  true,
  'https://maps.app.goo.gl/example3',
  true,
  false,
  true,
  NULL,
  false,
  true,
  true,
  false,
  NULL,
  true,
  'Premier point gagné ! Continuez ainsi.',
  'Félicitations ! Un croissant vous attend.',
  true
),

-- Boutique 4: Fleuriste
(
  'Fleurs & Cie',
  '23 Rue Maurice Berteaux, 78700 Conflans-Sainte-Honorine',
  '0130223344',
  'contact@fleurs-cie.fr',
  '1 bouquet offert au 8ème passage',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
  'fleurs-cie',
  'Fleuriste',
  '8',
  '1 bouquet offert',
  '2.092000',
  '48.993000',
  'Fleuriste passionné créant des compositions florales uniques pour toutes vos occasions.',
  'https://www.fleurs-cie.fr',
  'https://www.facebook.com/fleurs-cie',
  'https://www.instagram.com/fleurs-cie',
  NULL,
  NULL,
  'Mardi au samedi : 9h - 19h, Dimanche : 9h - 13h',
  'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=200',
  'fleuriste, fleurs, bouquet',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/fleurs-cie',
  true,
  'https://maps.app.goo.gl/example4',
  false,
  true,
  true,
  '1',
  true,
  false,
  false,
  false,
  NULL,
  false,
  'Merci pour votre confiance !',
  'Un magnifique bouquet vous attend en boutique.',
  true
),

-- Boutique 5: Librairie
(
  'Librairie Les Mots',
  '12 Boulevard Salvador Allende, 78700 Conflans-Sainte-Honorine',
  '0130112233',
  'contact@librairie-les-mots.fr',
  '15% de réduction au 4ème achat',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
  'librairie-les-mots',
  'Culture',
  '4',
  '15% de réduction',
  '2.087000',
  '48.989000',
  'Librairie indépendante proposant un large choix de livres, BD et jeux de société.',
  'https://www.librairie-les-mots.fr',
  NULL,
  'https://www.instagram.com/librairie-les-mots',
  NULL,
  NULL,
  'Mardi au samedi : 10h - 19h',
  'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=200',
  'librairie, livres, culture',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/librairie-les-mots',
  true,
  'https://maps.app.goo.gl/example5',
  false,
  false,
  true,
  NULL,
  false,
  false,
  true,
  false,
  NULL,
  true,
  'Bienvenue dans notre univers littéraire !',
  'Profitez de 15% de réduction sur votre prochain achat.',
  true
),

-- Boutique 6: Pharmacie
(
  'Pharmacie du Centre',
  '5 Place de la République, 78700 Conflans-Sainte-Honorine',
  '0130445566',
  'contact@pharmacie-centre.fr',
  '1 produit d''hygiène offert au 6ème passage',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800',
  'pharmacie-centre',
  'Santé',
  '6',
  '1 produit d''hygiène offert',
  '2.091000',
  '48.990000',
  'Pharmacie de proximité proposant conseils pharmaceutiques et produits de santé.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Lundi au samedi : 8h30 - 19h30',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=200',
  'pharmacie, santé, bien-être',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/pharmacie-centre',
  true,
  'https://maps.app.goo.gl/example6',
  false,
  false,
  true,
  NULL,
  false,
  false,
  true,
  false,
  NULL,
  false,
  'Merci pour votre fidélité !',
  'Un produit d''hygiène vous attend.',
  true
),

-- Boutique 7: Café
(
  'Café des Arts',
  '18 Quai Eugène le Corre, 78700 Conflans-Sainte-Honorine',
  '0130778899',
  'contact@cafe-des-arts.fr',
  '1 café offert pour 5 consommations',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80',
  'cafe-des-arts',
  'Restauration',
  '5',
  '1 café offert',
  '2.080000',
  '48.988000',
  'Café convivial avec terrasse vue sur la Seine, proposant boissons chaudes et en-cas.',
  'https://www.cafe-des-arts.fr',
  'https://www.facebook.com/cafe-des-arts',
  'https://www.instagram.com/cafe-des-arts',
  NULL,
  NULL,
  'Lundi au dimanche : 7h - 20h',
  'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=200&q=80',
  'café, restauration, terrasse',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/cafe-des-arts',
  true,
  'https://maps.app.goo.gl/example7',
  true,
  true,
  true,
  '1',
  true,
  true,
  true,
  false,
  NULL,
  true,
  'Premier point gagné ! Continuez à nous rendre visite.',
  'Un café vous attend, venez le récupérer !',
  true
),

-- Boutique 8: Magasin de vêtements
(
  'Mode & Style',
  '30 Rue de la Paix, 78700 Conflans-Sainte-Honorine',
  '0130667788',
  'contact@mode-style.fr',
  '20% de réduction au 7ème achat',
  gen_random_uuid(),
  'Nouveauté',
  'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
  'mode-style',
  'Mode',
  '7',
  '20% de réduction',
  '2.093000',
  '48.994000',
  'Boutique de prêt-à-porter proposant des vêtements tendance pour toute la famille.',
  'https://www.mode-style.fr',
  'https://www.facebook.com/mode-style',
  'https://www.instagram.com/mode-style',
  'https://www.tiktok.com/@mode-style',
  NULL,
  'Mardi au samedi : 10h - 19h',
  'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200',
  'mode, vêtements, prêt-à-porter',
  gen_random_uuid(),
  'https://madeinconflans.fr/pageweb/mode-style',
  true,
  'https://maps.app.goo.gl/example8',
  false,
  true,
  true,
  '1',
  true,
  false,
  false,
  false,
  NULL,
  false,
  'Merci pour votre confiance !',
  'Profitez de 20% de réduction sur votre prochain achat.',
  true
);

-- Note: Les UUID sont générés automatiquement avec gen_random_uuid()
-- Pour utiliser des UUID spécifiques, remplacez gen_random_uuid() par des valeurs UUID valides
-- Exemple: 'a16d195c-bb59-4f5f-bec8-83cf85b9efc4'

